name: Design Issue
description: Please report any design issues you encounter.
title: "[Design]: "
labels: ["design"]
projects: []
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: figma-link
    attributes:
      label: Figma Link
      description: Provide the corresponding Figma link for our quick reference her
      placeholder: ex. https://www.figma.com/file/abc123/My-Design-File
    validations:
      required: false
  - type: textarea
    id:
    attributes:
      label: The Procedure of Design Issue Management
      description: Please provide a detailed description of the issue you are facing.
      placeholder:
      value: |
        1. **Step 1**:
        2. **Step 2**:
        3. **Step 3**:
    validations:
      required: true
