name: Design Issue
description: Create a design issue to help us improve our design system.
title: "[Design]: "
labels: ["design"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: figma-link
    attributes:
      label: Figma Link
      description: Provide the corresponding Figma link for our quick reference here.
      placeholder: ex. https://www.figma.com/file/abc123
    validations:
      required: false
  - type: textarea
    id: procedure
    attributes:
      label: The Procedure of Design Issue Management
      description: Please describe the procedure of the design issue management.
      placeholder: ex. 1. Open the Figma file. 2. Check the design. 3. ...
      value: |
        1. Open the Figma file.
        2. Check the design.
        3. ...
      validations:
        required: true
